### ISSUE TITLE
Hunter Volley

### ISSUE THREAD

**Issue by sisisinononoeh** [AzerothShard/AzerothShard-Issues-ita#1]
non funziona il volley del hunter

skill eseguita: nulla
skill reale: http://wotlk.openwow.com/spell=58434

**Comment by Yehonal** [comment]
@mik1893 te che adori l'hunter, puoi confermare?

**Comment by mik1893** [comment]
non lo so devo provarlo - mi sembra strano che vada proprio zero... controllo bene

**Comment by Yehonal** [comment]
Il bug non è valido, il volley funziona
