### ISSUE TITLE
Shamy

### ISSUE THREAD

**Issue by latitante** [AzerothShard/AzerothShard-Issues-ita#100]
- Bug Shamy enha
- Non funziona StormStrike E Lava lash

**Descrizione**: Il bug sta tutto nei danni perchè giocando per molto tempo e avendo un tot equip con talenti giusti  e glifi i danni dovrebbero essere incrementati di un bel pò ma qui non lo è danni sempre  bassi 

**Attuale comportamento**: Attaualmente accade che uso la rotazione attivo tutto ma danni e crittoni non se ne vedono in bg  sto a fare solo figure di merda 

**Comportamento previsto**: Dovrebbe accadere che se attivo i talent piu l'aumento dei danni  che mi danno i glifi e i punti selezionati nei talenti quando si attivano dovvrei fare piu danno ma non lo è 

**Passi per riprodurre il problema**:
1. Verificare se i talent funzionano
2. Aumentare i danni 
3. Verifca dei glifi 

**Su che reame è stato testato:** Reame principale è stato Arena tournament 

*_è da quando gioco su azeoth una settimana piu che ho notato il problema dei danni è adesso ho ritestato secondo le vostre regole *_:

**Comment by latitante** [comment]
Per i  danni secondo me per talent equip glifi e ap e tutto l'equip dovrebbe essere come base 3500 4000 di danno sul gioco sto a fare massimo 2000 con i full pve

**Comment by xlollomanx** [comment]
Come ti ho scritto nell' altro report che hai fatto devi mettere dei calcoli SERI, ovvero calcoli precisi e non un tot al kilo. Segui il modello che ha scritto @mik1893 qui #42 (scritto per war ma la dinamica è sempre la stessa).
