### ISSUE TITLE
[Object] Mysterious Egg duration bug

### ISSUE THREAD

**Issue by Strizz** [AzerothShard/AzerothShard-Issues-ita#109]
Segnalo bug di durata del Mysterious egg, venduto dal Quartermaster del clan The Oracles, che attualmente ha una durata di 7 giorni prima di diventare Cracked Egg. Questo si può vedere nello screenshot allegato, in cui l'oggetto in questione è stato acquisito meno di 24h prima dello scatto.

Mentre secondo Openwow la durata dovrebbe essere di 8640 min, ovvero 6 giorni.

http://wotlk.openwow.com/item=39878#sold-by

Grazie dell'attenzione. 

![wow 2016-09-07 12-46-05-13](https://cloud.githubusercontent.com/assets/20110257/18309385/8530f9cc-74f9-11e6-944f-dfc03c46beca.jpg)

**Comment by Jagermaister95** [comment]
Purtroppo non sempre openwow è affidabile in quanto l'oggetto in questione ha durata di 7 giorni e non inferiore.
https://www.engadget.com/2008/11/30/the-oracles-mysterious-egg-is-a-must-get-for-pet-and-mount-coll/
o anche una discussione offy in cui si parla della diminuzione della durata dello stesso da 7 a 3 giorni:http://us.battle.net/forums/en/wow/topic/1765535074
