### ISSUE TITLE
[Chain-Quest] (Green Scepter Shard) The Nightmare Manifests

### ISSUE THREAD

**Issue by Raitoshu** [AzerothShard/AzerothShard-Issues-ita#110]
Buonasera volevo segnalare un bug in merito a The Nightmare Manifests. La quest è strutturata cosi: 
- Parlare con Rumulos
- Evocare Eranikus
- Uccidere i mob evocati da Eranikus ma NON Eranikus
- Aspettare che arrivi in aiuto Tyrande (fase bugga ovvero Tyrande non compare e ti segna missione fallita dopo qualche minuto di attesa).

server: azeroth shard / testata il: 5/09/2016

**Comment by Deteroch** [comment]
Bug non confermato, la quest funziona perfettamente visto che l'ho completata qualche minuto fa. Tyrande spunta soltanto quando il fight con Eranikus è iniziato(ho portato il boss sotto il 75%) e poi è spuntata Tyrande che mi ha aiutato nel fight del drago. Quando il boss raggiunge una certa soglia di vita(intorno al 30%) si trasforma di nuovo in elfo e redento torna nel sogno di smeraldo. In questo modo si completa la quest e si ottiene il Green Scepter Shard

**Comment by Deteroch** [comment]
Bug non confermato, la quest funziona perfettamente. Infatti dopo che Eranikus ha evocato la sua infinità di mob diventerà esso stesso targettabile, basta quindi soltanto cambiare target(dai mob a Eranikus) e dopo che la sua vita scenderà sotto una certa soglia(intorno al 75%) spunterà Tyrande che ci darà una mano nel fight. Arrivati,invece, (circa al 30%) Eranikus abbandonerà la sua forma dragonica per tornare elfo della notte e redimersi di fronte tutti quanti.
