### ISSUE TITLE
Quest : The Path of the Righteous

### ISSUE THREAD

**Issue by Roazar** [AzerothShard/AzerothShard-Issues-ita#113]
La quest situata in silithus chiede di prendere 200 carapace fragment dagli hive che stanno in tutta la regione, il bug sta che negli alveari molti insetti spawnano in punti in cui non e' possibile colpirli (specialmente nell'alveare ad est) e quindi rende molto piu' lunga la quest di quello che gia' e'

Testatostul server principale il 14/9

**Comment by Deteroch** [comment]
Bug non confermato, mi sono fatto il giro di tutti gli alveari del Silithus e i mob sono targettabili e killabili da chiunque(melee o caster) non vanno fuori dalla los e/o in texture.
