### ISSUE TITLE
Bug mana judgement

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#114]
Quando viene eseguita la spell judgement ( una di qualsiasi tipo tra le 3 disponibili ), in base al talent http://wotlk.openwow.com/spell=31878 il paladino dovrebbe ricevere il 25% del suo mana base. Quando viene effettuato il judgement su un assorb il mana non viene restituito.

**Comment by xlollomanx** [comment]
leggendo qui non sembra buggato http://www.mmo-champion.com/threads/672922-Paladin-Retribution-Tier-Judgement-of-the-Wise-quot-BUG!-quot

**Comment by Irome** [comment]
infatti.
