### ISSUE TITLE
Heal verso orda da personaggio ally non funzionante in dungeon

### ISSUE THREAD

**Issue by FrancescoGuerra** [AzerothShard/AzerothShard-Issues-ita#116]
Descrizione: Entrando come healer (Shaman, draenei) nel random dungeon finder sono stato messo in team con 4 membri horde nel dungeon Gundrak(Heroic), ho notato subito che non potevo curare in nessun modo i membri horde TRANNE quando castavo Chain Heal su di me, castando Chain Heal su di me le successive cure venivano indirizzate verso i membri del team più vicini.
Non è la prima volta che succede, ma di solito bastava fare out/in dal dungeon o semplicemente riloggare per evitare il problema(o marginarlo a solo un membro della squadra), questa volta NON sono riuscito a togliere il problema.

Attuale comportamento: Come descritto sopra non si riesce a curare membri della fazione opposta in dungeon (raid non ho ancora provato)

Comportamento previsto: Possibilità di curare tutti.

Passi per riprodurre il problema:
1. Uscire e rientrare dal dungeon, funziona spesso ma NON sempre
2. Logout e Login del personaggio, funziona spesso ma NON sempre
   Non sono passi che risolvono il problema perennemente, ma invece di lasciare il team senza healer provateci.

Su che reame è stato testato:Testato su reame principale

Quando è stato testato:  tra il giorno 16 Settembre 2016 e 17 settembre 2016

**Comment by Thurin93** [comment]
Il problema è stato risolto con gli ultimi fix al crossfaction. Qualora si ripresentassero commentare il post.
