### ISSUE TITLE
[bug drop instance classic] Guard Mol'dar

### ISSUE THREAD

**Issue by ghost1988** [AzerothShard/AzerothShard-Issues-ita#120]
**Descrizione**: Il suddetto NPC dovrebbe droppare la Gordok Inner Door Key

**Attuale comportamento**:  percentuale di drop intorno al 20%

**Comportamento previsto**: Percentuale di drop 100%

**Passi per riprodurre il problema**:

1. Uccidere l'NPC una volta e notare come non droppa la chiave

**Su che reame è stato testato:** Live 

**Quando è stato testato**:  25/09/2016

**Comment by Thurin93** [comment]
Ho ucciso l'npc 15 volte e per 15 volte è uscita la key. Segnalazione non valida.
