### ISSUE TITLE
Bug - Invisiblity mage

### ISSUE THREAD

**Issue by Attrito** [AzerothShard/AzerothShard-Issues-ita#121]
Oggi alle ore 18:47 sono entrato in arena , mi sono trovato contro warlock e priest, sono andato in invisiblity e mi hanno dottato, non penso sia stata la spell Detected Invisibility ( del lock ) , in quanto normalmente in invisibility non potrei vedere il party nemico , cosa che invece vedevo e riuscivo a targettare / mettere in focus

**Comment by Thurin93** [comment]
Ciao, le spell potrebbero essere state castate appena prima che entrassi in invisibility.
Inoltre ti ricordo che la spell si annulla se esegui una qualunque azione come attaccare o usare il blink e si annulla a seguito di danni anche aoe.
In soldoni non sono riuscito a riprodurre il problema senza la Detect invisibility.
