### ISSUE TITLE
[ICC 25H] Lady Death Wish

### ISSUE THREAD

**Issue by Adramelech91** [AzerothShard/AzerothShard-Issues-ita#123]
I bug da segnalare alla Lady sono principalmente due:
- Aggro che si resetta quando si passa di fase [Lo fa anche nelle altre tipologie di Raid (10, 10H, 25)]
- I Fantasmini appaiono troppo vicino al target e sono troppo veloci, di norma dovrebbero essere lenti, ed esplodono quindi troppo presto (a volte non riesci nemmeno a vederli) [Questo alla 25H]

**Comment by Dozzle** [comment]
Dunque, io confermo il bug, aggiungo quindi che, seguendo quanto è scritto su Wowwiki e Wowhead, alla 25h la Lady Deathwhisper dovrebbe far spawnare 1 solo Vengeful Shade (su AS ne spawnano 3 a velocità doppia e a 2 yd di distanza, quindi NON evitabili) alla volta, che dovrebbe colpire con una spell chiamata Vengeful Blast il pg targettato e tutti quelli presenti in un area di 20yd da costui, con un damage compreso tra 23160 e 24840.
Sul nostro server un dps plate con 43k di vita buffato riceve un danno compreso tra i 40k e i 50k, automaticamente un qualunque caster o healer viene oneshottato.
Riporto la descrizione di Wowwiki, che è la stessa anche per World of Warcraft Wiki:
"Vengeful Shade
Spell shadow deathsembrace  [Vengeful Blast]ω ϖ ω ϖ Melee range—Inflicts 23160 to 24840 Shadowfrost damage to all enemies within 20 yards of the target." 

http://et.worldofwarcraft.wikia.com/wiki/Lady_Deathwhisper

Vi pregherei di provvedere quanto prima al fix, poichè impedisce il progress di gilda e di ciascun player. Grazie.

**Comment by Elvyan93** [comment]
Sono daccordo, un bug simile del raid più importante dell espansione và revisionato immediamente

**Comment by Jagermaister95** [comment]
Salve a seguito delle numerose segnalazioni,presenti anche sul forum,il boss è stato testato più e più volte e dopo attenta analisi, iniziamo a verificare i punti da voi descritti:

- L'aggro del boss in tutte le sue modalità deve resettarsi nel momento in cui fasa(fine dello scudo di mana)
FONTI:http://wowwiki.wikia.com/wiki/Lady_Deathwhisper(After her shield is down, Lady Deathwhisper switches to a new set of abilities, she gets an aggro table (in effect her threat is reset) and also starts to melee and cast Frostbolt volley.)

- I fantasmini(Vengeful Shade) non sono troppo veloci nè sono invisibili nè fanno da 40k a 50k di danno. Il loro danno è compreso tra 23k e 25k massimo come nella descrizione di wowwiki. Preciso inoltre che l'esplosione del "fantasmino"(Vengeful Blast) avviene nell' esatto momento in cui SOLO il player e il fantasmino entrano in contatto e non prima o dopo quindi l'esplosione non avviene troppo veloce o a caso.

A conferma ulteriore di ciò che ho scritto posto il video offy dei PARAGON dove viene mostrato tutto quello che ho citato; https://www.youtube.com/watch?v=J2b-68A5Zi0.

In fine, consiglio di evitare segnalazioni parziali e/o prive di fondamento senza essersi precedentemente accertati tramite le fonti ufficiali di ciò che dovete segnalare.

**Comment by Dozzle** [comment]
Avrei dovuto screenare i 50k subiti dal vengeful blast.
Non ho scritto che l'esplosione avviene a caso nè ho parlato di aggro del boss.
Avrei dovuto anche screenare i 3 fantasmi che sono apparsi a 1yd da me (impossibile scappare) e che mi hanno targettato.
Aggiungo che se durante il boss, che viene fatto alla perfezione, la gente viene oneshottata in 2 fase, un motivo c'è ed è sicuramente questo.
La prossima settimana torno con il solito gruppo e faccio screen o magari anche video. Se apro una segnalazione non è perchè sono idiota, impazzito o ignorante.

**Comment by Adramelech91** [comment]
Come al solito i DEV prendono sottogamba e con superficialità le segnalazioni: come detto da Dozzle faremo video sulla questione con relativi LOG dei danni. Volete le prove? Ve le daremo, parola di Adra.

**Comment by Attrito** [comment]
Confermo il post di Adra, anche a me è capitato di vedere un fantasmino spawnare molto vicino ai player

**Comment by Arkan0r** [comment]
Il boss è stato controllato ieri da un GM in live mentre una gilda lo eseguiva e non è stato riscontrato alcun bug. Chiudo la segnalazione

**Comment by Dozzle** [comment]
Sorrido, siete molto scaltri...
