### ISSUE TITLE
Quest Darkshore: How big a threat

### ISSUE THREAD

**Issue by Roazar** [AzerothShard/AzerothShard-Issues-ita#128]
in questa quest bisogna trovare uno qualsiasi dei campi dei corrupted furborlg ma anche se ci vai al centro non te la segna mai completa
testato il 01/10 sul server principale

**Comment by Thurin93** [comment]
Ciao. Ho appena testato la quest e me l'ha completata senza problemi. La quest è stata consegnata e non sembra avere difetti.
