### ISSUE TITLE
[QUEST] Roll the Bones

### ISSUE THREAD

**Issue by ghost1988** [AzerothShard/AzerothShard-Issues-ita#129]
**Descrizione**:La quest Roll the Bones risulta bugga perchè i mob che dovrebbero droppare le ossa non le droppano.

**Attuale comportamento**:  Ne ho uccisi una 30ina di quelli segnati dalla quest senza risultato
**Comportamento previsto**: Dovrebbe dropparne al massim uno ogni 2 vedendo un video (drop 50%)
**Passi per riprodurre il problema**: Uccidere i suddetti dinosauri
**Su che reame è stato testato:**Live
**Quando è stato testato**:  01/10/2016

**Comment by Thurin93** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/185

**Comment by ShinDarth** [comment]
Fixato, grazie per la segnalazione.
