### ISSUE TITLE
Probabili differenza tra test server e game server

### ISSUE THREAD

**Issue by dany918** [AzerothShard/AzerothShard-Issues-ita#130]
Ciao a tutti,
Come da titolo vorrei suscitare questo problema;
Visto le varie incongruenze riscontrate dai tester ad icc(Lady 25h-sindra fase 3 ''stack'', DPS inferiore al normale,ecc...) e noi che giochiamo sul server nudo e crudo, non vorrei che i 2 server non sono  perfettamente sincronizzati fra di loro come dovrebbero essere.
Ormai sono passati un paio di mesi da quando e stato messo il nuovo core e noi Player che giochiamo esclusivamente per fare PVE vorremo anche fare qualche progress...
Grazie della gentile attenzione

**Comment by Arkan0r** [comment]
Il boss è stato controllato da un GM in live, il quale ha riscontrato che non ci sono bug quindi non c'è differenza tra server dev e live.

**Comment by Dozzle** [comment]
Siete veramente dei furbi. Non dico altro...
