### ISSUE TITLE
Quest Darkshore: Escape Through Force

### ISSUE THREAD

**Issue by Roazar** [AzerothShard/AzerothShard-Issues-ita#131]
una volta arrivato alla fine della quest (vicino all'orso) l'npc va in texture e non si completa la quest
testato il 2/10 sul server principale

**Comment by Thurin93** [comment]
https://github.com/AzerothShard/AzerothShard-Issues-ita/issues/119
Per favore usiamo il tasto cerca prima di aprire issue già aperte, ma soprattutto cerchiamo di usare il modulo pre-impostato.
