### ISSUE TITLE
Bug seal of corruption

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#133]
Il suddetto seal http://wotlk.openwow.com/spell=53736 dovrebbe applicare una stack per ogni meele swing effettuato( quindi anche spell meele strike ). Ciò non accade. Ho testato sia con il crusader strike che con il divine storm.

**Comment by xlollomanx** [comment]
Non credo sia un bug. Citando http://wowwiki.wikia.com/wiki/Seal_of_Vengeance : "Note that only normal melee swings can apply the debuff, with the exception of Hammer of the Righteous. Attacks like Divine Storm and Crusader Strike will not apply or refresh the DoT, though they do gain the direct holy damage bonus if the DoT has 5 stacks. "

**Comment by Irome** [comment]
Confermo.
