### ISSUE TITLE
Non c'è la daily quest dei Kalu'ak a Kamagua

### ISSUE THREAD

**Issue by Polemox** [AzerothShard/AzerothShard-Issues-ita#136]
Scrivo per segnalare il non funzionamento di una daily dei Kalu'ak. Più precisamente la daily quest, "The way to his hearth", una delle 3 daily quest che si possono fare per i Kalu'ak, che dovrebbe essere data da Anuniaq a Kamagua, non pùò essere fatta semplicemente perchè l'npc in questione non la tiene. Ovvero: la quest non si può fare perchè l'npc che la dovrebbe avere non ce l'ha. Anuniaq dovrebbe avere la quest. Ho verificato la situazione a distanza di tempo per vedere se per caso era stata risolta, ma invece no. Non l'ho testata su altri reami, ma è chiaro che essendo i kalu'ak una fazione implementata alla wotlk, la quest dovrebbe essere presente.

**Comment by Helias** [comment]
La quest la da devi svolgere la chain qui presente http://wotlk.openwow.com/quest=11573 fino a Street "Cred", per poi svolgere http://wotlk.openwow.com/quest=11469 e te la da.
