### ISSUE TITLE
Hijal Summit : Archimonde (Hand of Death)

### ISSUE THREAD

**Issue by Roazar** [AzerothShard/AzerothShard-Issues-ita#137]
**Descrizione**: Durante Hijal Summit, arrivati ad Archimonde, Improvvisamente fa una spell chiamata Hand of Death che uccide tutti all'istante, quando invece questa e' la mossa che fa quando va in bersek

**Comportamento previsto**: Se si riesce a portare Archimonde sotto il 10% entro 10m la spell non dovrebbe proprio partire

**Passi per riprodurre il problema**:
1. Fare Archimonde
2. Aspettare che faccia la spell prima dei 10m
   **Su che reame è stato testato:** Reame principale 

**Quando è stato testato**: 12/10

**Comment by Deteroch** [comment]
Ciao, quello che dici tu non è propriamente corretto, cito testualmente wowwiki in merito al fight di Archimonde inerente alla spell Hand of Death:  100k shadow damage to everyone in the raid, used 9 minutes after Archimonde is engaged or if he reaches Nordrassil. Quando dice if he reaches Nordrassil significa non appena il boss raggiunge il 10% di vita e questo accade sempre. Quello che invece non accade(leggendo il tuo report) è la seguente spell ausiliaria(citando sempre wowwiki): Tyrande gives the raid a 60 second invulnerability (de-)buff (Protection of Elune). In questo modo Tyrande rende immune il raid in quei 60 secondi di fight. Bisogna testare quindi se la spell protection of Elune viene attivata non appena il boss raggiunge il 10% di vita e non la spell Hand of Death che funziona correttamente.
