### ISSUE TITLE
quest: shutting down manaforge B'naar

### ISSUE THREAD

**Issue by comix1988** [AzerothShard/AzerothShard-Issues-ita#138]
La quest in oggetto è funzionanate,ma una volta completata non è più possibile consegnarla,anche se dal quest log risulta "complete".

**Comment by comix1988** [comment]
altre info sulla quest:
la quest si prende e si consegna all'npc Spymaster Thalodien presso area 52 a netherstorm.
Per completarla bisogna droppare la chiave B'naar Access Crystal dal mob Overseer Theredis e poi utilizzarla sul pannello di controllo per spegnerlo.
La fase di shut down dura 2 min,finita quella fase la quest è stata completata.

**Comment by Thurin93** [comment]
Ciao.
Ho appena testato la quest ed è completamente funzionante. Completata dopo aver droppato la chiave dal mob, uccisi i vari technician che arrivavano per tentare di fermare lo shutdown e al termine dei due minuti la quest mi è risultata completata e anche presente nel quest log.
Sei sicuro di averla completata e fatta per bene?
![immagine](https://cloud.githubusercontent.com/assets/16744874/19620986/5b74581a-9888-11e6-82b7-573733719f88.png)

**Comment by comix1988** [comment]
ciao,
io ho aperto ticket in game e mi è stata sistemata (ho lasciato aperto discussione sul bug tacker in quanto non sapevo se era stata fixata).
anche a me dopo aver droppato il quest item e aver concluso la fase che durava 2min la dava completa sul quest log,ma quando andavo a consegnarla il pulsante "complete" dell'npc rimaneva grigio come il punto di domanda sopra di esso.
