### ISSUE TITLE
prorblema prof 25hm

### ISSUE THREAD

**Issue by lavezzzi010** [AzerothShard/AzerothShard-Issues-ita#139]
![wowscrnshot_101716_230849](https://cloud.githubusercontent.com/assets/22897643/19456148/753d6cee-94c0-11e6-91fd-2be011dbdcfc.jpg)
il problema è che avendo il debuff rosso la melma verde ti targetta, viceversa quando si ha il debuff verde la rossa targetta

**Comment by Jagermaister95** [comment]
Salve, la tua segnalazione non è valida per un semplice motivo; questo non è un bug in quanto reporto video offy dei Pragon (https://youtu.be/jv93ko3WeK8?t=125) in cui si vede chiaramente al minuto 2:11/2:15 in cui il player ha il debuff della melma rossa ma viene targettato ugualmente dalla verde.
Accertati della segnalazione utilizzando fonti attendibili prima di correre al bug. Grazie.
