### ISSUE TITLE
[QUEST] Bug Chain Quel'Delar

### ISSUE THREAD

**Issue by xlollomanx** [AzerothShard/AzerothShard-Issues-ita#14]
Durante la quest http://wowwiki.wikia.com/wiki/Quest:The_Halls_Of_Reflection_(Horde) ho notato qualcosa di anomalo. Nella quest si deve entrare a Hall of Reflection. Li poco dopo essere entrati dovrebbe spawnare dopo un breve dialogo una spada che deve essere killata. Una volta fatto questo appare il messaggio "quest complete", tuttavia la quest non è effettivamente completabile perchè non viene fornito l' item successivo, ovvero http://www.wowhead.com/item=50254/subdued-queldelar. Nel video https://www.youtube.com/watch?v=-e9LTjYiRJw al minuto 21:25 circa viene mostrata la spada che fornisce sottoforma di loot l'item successivo della chain, cosa che invece non accade. La spada non è lootabile.

**Comment by Gargarensis** [comment]
<img>https://cdn.discordapp.com/attachments/192631460379754496/204367247194456065/unknown.png </img>
Potete ritestare la quest? A me ha funzionato perfettamente

**Comment by mik1893** [comment]
ho provato ora, funziona se si e' in gruppo, non funziona se si e' in raid

chiuso - chain funzionante
