### ISSUE TITLE
bug QUEST rep Argent Tournament "The Black Knight's Fall" (Icecrown - zona esterna ToC)

### ISSUE THREAD

**Issue by Raitoshu** [AzerothShard/AzerothShard-Issues-ita#141]
In seguito a test effettuati con GM Thurin in data 29/10/16 , richiedo fix per la quest "The Black Knight's Fall".
Spiegazione quest:
fase 1) montare sulla cavalcatura ed equipaggiare lancia;
fase 2) parlare con npc squire cavin per evocare il boss The Black Knight;
fase 3) killare il boss con le mosse speciali della cavalcatura.
bug 1 : non si riesce ad evocare il boss tramite l'npc sqire cavin.
bug 2: al GM Thurin si è verificato invece un altro bug ovvero il boss veniva evocato correttamente ma agiva in modo strano (chiedere a thurin per ulteriori spiegazioni in merito).

**Comment by Thurin93** [comment]
Momentaneamente confermo il bug in quanto ho provato la quest in prima persona. Quando l'ho summonato io era come se andasse a speed 500 e mi ha inflitto 10k di danno con un autoattack. Va testata meglio.

**Comment by pati3nc3** [comment]
Ho appena fatto la quest con conseguente achi e funziona. Come da classic mode, si sale sul cavallo senza problemi, si parla con l'npc e viene evocato il boss che viene fightato in 2 fasi; 1) in mount con le classiche spell. 2) in player mode.

**Comment by Helias** [comment]
Confermo, la quest non è buggata
