### ISSUE TITLE
kickin-nass-and-takin-manes

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#149]
http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes la suddetta quest non funziona. Appena startata dovrebbe evocare un npc per fare la quest ma ciò non accade.

**Comment by Helias** [comment]
Appena testata, la quest funziona, l'NPC se non spunta lo puoi richidere direttamente a  Stefan Vadu parlandoci, una volta ottenuto un NPC ti basta uccidere i troll, una volta uccisi utilizzi il quest item "Stefan's Steel Toed Boot"

![nass](https://cloud.githubusercontent.com/assets/519778/20627040/df38f656-b31d-11e6-9932-042461a5c787.png)

**Comment by pati3nc3** [comment]
Parlandogli di nuovo non appare, provato prima ... non saprei

Il giorno 25 nov 2016, alle ore 14:46, Stefano Borz? <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Closed #149<https://github.com/AzerothShard/AzerothShard-Issues-ita/issues/149>.

-

**Comment by Helias** [comment]
Prova ad abbandonare la quest e a riprenderla, stai senza mount mentre accetti la quest
