### ISSUE TITLE
[SPELL] Dk, Dancing Rune Weapon non funziona

### ISSUE THREAD

**Issue by Harlokk** [AzerothShard/AzerothShard-Issues-ita#16]
Salve, stavo testando nel server di testing il dk blood e ho notato che la spell [Dancing Rune Weapon] viene lanciata, però sembra che non faccia nulla, ho controllato il combat logs e non casta nessuna spell che dovrebbe castare, sotto la mia barra compare la spell attiva, tutta via non fa proprio nulla.

Dancing Rune Weapon Dovrebbe funzionare in questa maniera : Dovrebbe castare le spell che fa il dk, imitandole e facendo quanto meno il 50% del danno fatto dal dk, quindi se lanciassi un hearth strike che fa 12 k, quello del pet[Dancing Rune Weapon] dovrebbe fare 6k, inoltre ho letto che Dancing Rune Weapon dovrebbe mettere a sua volta dei dots, quindi dovrebbero comparire sul target, 2 dots miei [frost fever e blood plague]  e 2 dots del pet. 

Inoltre c'è un'altra cosa, che non mi è chiara, mi è sembrato di aver letto che comunque quei 2 dots in più dovrebbero benificiarmi in un qualche modo, non so se sono le spell del dk che devono tener conto dei dots in più, per esempio se heart strike fa il 10% di danno in più per dot, dovrebbe farne il 40% se fosse così che dovrebbe funzionare. Altrimenti sono le spell del pet che dovrebbe benificiare dei suoi stessi dots, questa cosa è ancora da chiarire.
Cmq sia il danno minimo del pet dev'essere la metà del danno che fa il dk, però è il danno minimo che fa, secondo me dovrebbe aumentare tenendo in cosiderazione i dots, e forse dato che Dancing Rune Weapon è considerato un pet anche le sue spell potrebbero crittare a loro volta.

Spero sia chiaro ciò che ho scritto, secondo me a rigor di logica la spell dovrebbe funzionare in questa maniera, una possibile fonte che ho trovato è questa : http://forum.warmane.com/showthread.php?t=188991

La parte interessante : "this is a huge burst tool for us, as it now copies diseases (and thus deals more HS damage) , it's wise to use it before applying diseases "

Confermo la mia idea precedente, l'heart strike del dk dovrebbe tenere in considerazione anche i dots messi dal pet, quindi 4 dots. 
fonte: https://github.com/TrinityCore/TrinityCore/issues/6192
Parte interessata: "Is this fixing the diseases problem? Now the DRW reproduce the attack like IT and PS but doesn't apply the dot's!
When we know that the damage of the HS depends of the number of diseases on the target and we've only half of these."

l'ho trovata adesso girando un pò.

Fatemi sapere cosa ne pensate,
Cordiali saluti Axel

**Comment by mik1893** [comment]
Dovremo probabilmente copiare il fix da trinitycore

**Comment by Harlokk** [comment]
D'accordo, appena lo inserite proverò a testarlo, però non sono sicuro che esista un fix vero e proprio neanche dal trinity core, forse è un pò complicato da scriptare? Conosco C++ per cui pensare tutta sta meccanica in codice lo trovo abbastanza complicato e contorto

**Comment by Harlokk** [comment]
ah d'accordo, e allora perchè sulla maggior parte dei server questa spell è sempre bugga e non funziona mai?

**Comment by Harlokk** [comment]
Comunque fatemi sapere quando l'avete aggiunto che proverò a testarlo

**Comment by Harlokk** [comment]
ho controllato altri bug tracker di altri server di woltk in circolazione, dancing weapon rune non è fixata neanche lì, molte persone che vorrebbero giocare il dk blood non possono perchè compremette l'intera classe, nel vostro server ufficiale funziona parzialmente, ma un pò di dps lo fa, se riusciste a fixarlo completamente, quindi mettendo i dots e facendo funzionare bene dwr e hs (ovvero che tenga conto dei 2 dots messi da dwr), potreste far circolare la voce su gli altri server che la classe del dk blood è completamente fixata e portarvi un pò di gente che giocerebbe dk solo per quello

**Comment by mik1893** [comment]
Cancellati commenti inutili - e' un bug tracker, non un forum. 
La patch e' importata, applicazione dei disease corretta, manca il danno bianco. Verra attivata da stasera/domattina sul server di test

**Comment by Harlokk** [comment]
Sul server di test non è ancora stato aggiunto, ho provato adesso

**Comment by mik1893** [comment]
ma perche non joini la chat relativa ai test? cosi evitiamo di usare il bug tracker come una chat

**Comment by mik1893** [comment]
fixato completamente e funzionante - provato su test con i player
