### ISSUE TITLE
Bug Quest Toxic Tolerance

### ISSUE THREAD

**Issue by Glarador** [AzerothShard/AzerothShard-Issues-ita#165]
**

**Descrizione**: Ero ad un goro per farmare la mount del ravasaur

**Attuale comportamento**: I venomhide ravasaur non attaccano il veleno sul player

**Comportamento previsto**: dovrebbero attaccare il veleno sul player per venti volte 

**Su che reame è stato testato:** Reame principale

**Quando è stato testato**:  26/04/2017

**Comment by Thurin93** [comment]
Spiego meglio il problema: I Venomhide Ravasaur per il completamento della quest devono avvalenare il player. Questo evento deve ripetersi 20 volte.
Comunque dopo alcuni test ti spiego il procedimento per chiudere la quest: vieni avvelenato solo se attacchi i mobs, per cui ti consiglio di rimuovere l'arma e fare una bella scazzottata con i dinosauri ^^
