### ISSUE TITLE
Bug poison pet

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#17]
Il bug consiste in uno snare del pet ovvero avendo un rog up sul player, con crippling poison attiva sul player, il pet viene automaticamente snarato dalla poison anche non avendola addosso il che fa presumere che venga influenzato dalla poison sul lock.

**Comment by Irome** [comment]
Guarda questo video: it.tinypic.com/r/346kk15/9

Quel veleno è un ''Singolo bersaglio''.. Ovvero il rogue si scaglia su di te e menandoti ti applica questo veleno che ti rallenta del 70% per 12 secondi che vengono riattivati ogni volta che questo veleno ti affligge.

Mentre il pet non è in nessun modo afflitto da questo veleno se non quando il rogue si gira su quest'ultimo avvelenandolo. In questo caso risulterà rallentanto come per il primo target:

http://it.tinypic.com/r/25a80eu/9

Nel primo video mostro come il mio Hunter venga rallentato dall'effetto di questa poison e che il mio pet non sia in nessun modo rallentato. Nel secondo video invece mostro che il veleno è ancora attivo su di me e scade poco dopo che il mio pet viene avvelenato.

Quindi è un bug infondato e falso. Chiudo la issue
