### ISSUE TITLE
BUG SNARE REMOVAL TREE FORM

### ISSUE THREAD

**Issue by Hashtagrekt** [AzerothShard/AzerothShard-Issues-ita#172]
Se si è soggetti ad uno snare/root mentre in tree form, lo shapeshiftare di nuovo in tree form non rimuove il suddetto snare/root, mentro dovrebbe rimouverlo. 
Per riprodurre il bug basta creare una macro:
/cast !Tree of Life
Ci si fa snarare e si utilizza questa macro, si osserva che lo snare non si toglie ma rimane. Se fatto con qualsiasi altra form il bug non si presenta.
Il bug è stato testato sul realm Blackrock di Warmane in data 09/06/17.

**Comment by ShinDarth** [comment]
cosa c'entra Warmane?
