### ISSUE TITLE
Paladin Mount scaling with Haste

### ISSUE THREAD

**Issue by Nooblydone** [AzerothShard/AzerothShard-Issues-ita#181]
Buongiorno a tutti :O
**Descrizione**:  Le mount specifiche del Paladino sono buggate. Il cast è più veloce quanta più haste si ha, come fosse una spell.

**Attuale comportamento**: Attualmente summonare la propria mount risulta più veloce se si ha più haste.

**Comportamento previsto**: Il cast dovrebbe essere fisso a 1.5 sec!

**Passi per riprodurre il problema**: Mettere su haste su un paladino, e notare per esempio che il cast della Flash of Light (che è 1.5 di base, e viene giustamente velocizzato) è uguale a quello della mount.

**Su che reame è stato testato:** Reame principale! Porto due screenshot dove si vede la mia terribile UI ed il fatto che il cast è velocizzato :V

Flash of Light: http://imgur.com/a/ESW7V
Charger (Mount): http://imgur.com/a/XdvHV
I cast sono stati fatti con 507 Haste Rating. Ma funziona con qualsiasi amount.

**Quando è stato testato**:  7/07/2017

PS. Ho motivo di credere il bug possa esistere sia col DK che col Warlock. Non posso testare su queste due classi ma un controllo veloce mi sembra appropriato.
PPS. Il titolo in inglese mi ispirava di più. Heh.

**Comment by Nooblydone** [comment]
Aggiungo che ho testato il bug con ulteriori mount; si presenta anche con la Crimson Deathcharger (reward della Shadowmourne quest chain) http://wowwiki.wikia.com/wiki/Reins_of_the_Crimson_Deathcharger

**Comment by xeela** [comment]
Ho provato con il dk e con il lokko e non si verifica questo bug

**Comment by Jagermaister95** [comment]
Confermo che tutte le mount di classe di paladino,lokko, dk e il Crimson Deathcharger sono influenzati dall'haste riducendone il tempo di cast. Grazie per la segnalazione.

**Comment by Yehonal** [comment]
@Nooblydone ci stiamo occupando di questa segnalazione, potresti intanto ricopiarla nel nuovo laboratory? https://azerothshard.org/laboratory/category/bugs/

Possiamo continuare li e chiudere qui

**Comment by Yehonal** [comment]
Tradotta per il repo ufficiale: https://github.com/azerothcore/azerothcore-wotlk/issues/554

**Comment by Yehonal** [comment]
Questo bug è stato fixato e sarà disponibile al prossimo aggiornamento del core
