### ISSUE TITLE
Defile & CO possono finire sul Main Tank

### ISSUE THREAD

**Issue by Nooblydone** [AzerothShard/AzerothShard-Issues-ita#184]
**Descrizione**: Spell come Defile (http://www.wowhead.com/spell=72762/defile) e Legion Flame (http://www.wowhead.com/spell=66199/legion-flame) possono targettare il Main Tank (cioè chi ha aggro al momento sul boss)

**Attuale comportamento** - **Comportamento previsto** : Queste due spell possono targettare chi ha aggro sul boss al momento, mentre NON dovrebbe essere possibile. Tutti gli altri target sono "papabili", ma non il Main Tank. 
Ho notato solo queste 2 spell ma probabilmente il problema sarà generale con tutte le spell di questo tipo.

**Passi per riprodurre il problema**: Andare con un gruppo di alcune persone da Lord Jaraxxus o Lich King e aspettare che le sopracitate spell targettino il Main Tank :D

**Su che reame è stato testato:** Reame principale! 

**Quando è stato testato**:  Per il defile, circa 2 settimane fa, direi i primi giorni di Luglio. Per le legion flame, la settimana scorsa. Quindi diciamo dal 1/07/2017 al 7/07/2017!

**Comment by Veresa** [comment]
"Defiles the area under a random target" prima riga della spell Defile, se questa può targhettare il tank allora anche tutte le altre possono.

**Comment by Nooblydone** [comment]
Sì, nel tooltip della spell c'è scritto che può targettare un random target ma il Main Tank è escluso. Spesso la Blizzard non specifica tutto nelle descrizioni rapide di determinate spell / talenti.

**Comment by xeela** [comment]
@ShinDarth

**Comment by xeela** [comment]
http://wow-ladies.livejournal.com/12584733.html può targettare anche un tank
