### ISSUE TITLE
[VENDOR DK] Quartermaster Ozorg

### ISSUE THREAD

**Issue by ghost1988** [AzerothShard/AzerothShard-Issues-ita#19]
Manca il Quartermaster Quartermaster Ozorg
http://www.wowhead.com/npc=28512/quartermaster-ozorg
E i relativi pezzi che vende
(nell'attuale core abbiamo solo uno dei due set che vende)

**Comment by Gargarensis** [comment]
Al momento è spawnato a Dalaran, in seguito verrà probabilmente spostato
