### ISSUE TITLE
NPC monotexure a Booty Bay

### ISSUE THREAD

**Issue by Irome** [AzerothShard/AzerothShard-Issues-ita#2]
A Booty Bay ci sono due NPC Goblin Commoner in monotexure ad altri due NPC umani che hanno lo stesso nome dei Goblin.

Posto qui la foto per rendere chiaro il bug:
https://i.gyazo.com/fa5ad1a43f812f6dc316f0a4765c968d.png

**Comment by Yehonal** [comment]
Eri in gm off?

**Comment by Irome** [comment]
Si ero in gm off, ma non ho provato anche con i comandi da gm attivi.
