### ISSUE TITLE
[Racial] Blood Fury bug grafico

### ISSUE THREAD

**Issue by Harlokk** [AzerothShard/AzerothShard-Issues-ita#22]
Salve, mi sono accorto di un bug grafico riguardate [Blood Fury], segna che dovrebbe dare 6 di attack power, mentre nel caso l'usassi e controllassi effettivamente quanta ap mi da me la da correttamente: 
![wowscrnshot_071816_180349](https://cloud.githubusercontent.com/assets/13575586/16921580/571cc692-4d12-11e6-960f-4393f9b003c3.jpg)
![wowscrnshot_071816_180928](https://cloud.githubusercontent.com/assets/13575586/16921708/e1111ed4-4d12-11e6-8fdb-6a16cf269627.jpg)

Prima screen segna 6 ap, la seconda fa vedere effettivamente quanto ha dato.

**Comment by mik1893** [comment]
bug visivo lato client, infixabile. Non e' buggata la spell, che funziona correttamente.
