### ISSUE TITLE
[DA TESTARE] Battlegrounds per sistema crossfaction e join specifico

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/AzerothShard-Issues-ita#24]
E' necessario testare i battlegrounds per avere dei feedback sullo status. Attualmente il sistema funziona così:

**1) RBG ( Arathi, Warsong, Eye , Isle )**

Attualmente il sistema sposta gli orda negli ally e gli ally negli orda ( per effettuare un test brutale ) successivamente verrà randomizzato.

Va testato che i punti vengono distribuiti correttamente ai vincitori, anche se di fazione opposta.

**2) JOIN SPECIFICO ( Tutti i BG )**

In questa modalità non è presente il sistema di "switch" della fazione pertanto è possibile joinarlo in 3 modi:

 1. in singolo -> verrai piazzato nella tua fazione
 2. in un party a fazione unica -> verrai piazzato con tutto il party nella tua fazione
 3. in un party a fazione mista -> verrai piazzato nella fazione del leader del tuo party

Chi joina specifico, deve essere consapevole di questo.

Queste due modalità permettono di utilizzare i battlegrounds in QUALSIASI modo, anche quello blizzlike.

Testate e tiriamo fuori le problematiche ( che sicuramente ci saranno )

**ATTENZIONE**: il comando .appear se utilizzato in un BG rende neutrale l'utilizzatore! pertanto **NON UTILIZZATELO**

**Comment by mik1893** [comment]
fixato e funzionante
