### ISSUE TITLE
[DA TESTARE] Lista contenuti da testare prima della migrazione

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/AzerothShard-Issues-ita#26]
@mik1893 ha creato qui un foglio excel che potete commentare con i test effettuati sui principali contenuti del game:

https://docs.google.com/spreadsheets/d/112rI5SY7QRLOWNgDpiAZ8bGu6lc3k9adGF04E8bYiR4/edit#gid=0

**Comment by mik1893** [comment]
per il momento il content presente e' piu che sufficiente. Rimane da sistemare il join bg crossfaction con randomizzazione (vedi altra issue)
