### ISSUE TITLE
[DA TESTARE] Titoli honor

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/AzerothShard-Issues-ita#27]
E' necessario testare il sistema dei titoli honor che abbiamo importato.

Il sistema è semplice: più honored kills hai più sale il titolo ( @mik1893 se possibile spiegala meglio te )

Cortesemente testatela il prima possibile così che possiamo chiudere questo lavoro nella nostra lista dei TODO.

**Comment by xlollomanx** [comment]
Ho provato a testare questi titoli seguendo questo format https://moltenwow.wordpress.com/2012/08/20/molten-wow-wotlk-title-progression-system/ , tuttavia dentro al bg mi sono trovato davanti qualcosa di strano. 
![wowscrnshot_072016_122535](https://cloud.githubusercontent.com/assets/6764804/16983570/aeea05c4-4e75-11e6-9f8a-6a9f0289519a.jpg)
![wowscrnshot_072016_122546](https://cloud.githubusercontent.com/assets/6764804/16983572/b4bff490-4e75-11e6-97c4-39fa31284a13.jpg)

Come si puo vedere faccio kill dentro al bg, però quando vado a vedere nelle stats del pg non mi vengono contate le kill fatte e non ricevo neanche honor.

**Comment by Yehonal** [comment]
Potresti cortesemente provare con delle kill in join specifico o semplicemente in open world, per vedere se te le segna o meno?

**Comment by xlollomanx** [comment]
il join era specifico. Ora provo in open world

**Comment by Yehonal** [comment]
@mik1893

**Comment by mik1893** [comment]
funzionava tutto, bastava cambiare il tipo di server nel worldserver.conf e rimuovere il controllo sull ip.
