### ISSUE TITLE
[DA TESTARE] Esperienza aumentata nei BG 

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/AzerothShard-Issues-ita#28]
Abbiamo importato il sistema di esperienza aumentata nei BG lvl < 80

Andrebbe testato un bg di lvl basso ( ad esempio con pg lvl 19 ) e controllare che vi dia un botto di esperienza:

attualmente è settata a 30x

**Comment by xlollomanx** [comment]
Ho testato questa meccanica con 2 pg livello 19, uno orda, l' altro ally. Ho ottenuto i seguenti risultati:

- killando ally con orda ho ottenuto 1 punto exp

- killando orda con ally ho ottenuto 2 punto exp

ecco uno screen dove mostra l'exp ottenuta: https://cdn.discordapp.com/attachments/192631460379754496/205255484842704897/WoWScrnShot_072016_113037.jpg

**Comment by Yehonal** [comment]
@xlollomanx lo screen puoi allegarlo anche direttamente tramite github, per la prossima volta :)

cmq grazie per il report

**Comment by xlollomanx** [comment]
Ora dopo gli ultimi fix con 2 pg livello 19 ottengo 60 exp per entrambe le fazioni 
![wowscrnshot_072116_175904](https://cloud.githubusercontent.com/assets/6764804/17029875/56c0b3e0-4f6d-11e6-81f0-a176b7d5efaf.jpg)
![wowscrnshot_072116_175956](https://cloud.githubusercontent.com/assets/6764804/17029878/57bdb9e6-4f6d-11e6-9289-8549fe82650c.jpg)

**Comment by mik1893** [comment]
funziona
