### ISSUE TITLE
[BUG] Crossfaction party

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/AzerothShard-Issues-ita#29]
Attualmente il sistema del crossfaction ha un piccolo bug:

quando si lefta il party misto la fazione non si resetta se non cambiando zona o riloggando.

Verrà fixato a breve

**Comment by mik1893** [comment]
risistemo asap il crossfaction con anche le nuove funzioni importate per il bg, cosi da sistemarlo a posto

**Comment by mik1893** [comment]
fixato tutto quanto e testato
