### ISSUE TITLE
[Warlock] I pet non vanno verso il target quando si usano le spell del pet

### ISSUE THREAD

**Issue by Ualock** [AzerothShard/AzerothShard-Issues-ita#30]
https://github.com/AzerothShard/AzerothShard-Ita-Wotlk/issues/20

Sul nuovo core si ripresenta il vecchio problema: ad esempio se uso spell lock del felhunter e il pet è lontano dal target, la spell non parte, mentre era stato fixato ovvero il pet si avviava verso il target e quando era in range castava spell lock.

A volte capita anche che bisogna premere due tre volte su spell lock prima che la spell parta (ovviamente quando il pet è in range) 

si possono ripescare i vecchi fix e metterli nel nuovo core?

**Comment by mik1893** [comment]
Si Certo - Lo segno da fare per release 1.1 meta agosto

**Comment by mik1893** [comment]
anticipato visto che abbiamo guadagnato un giorno - gia importato sul core nuovo
