### ISSUE TITLE
[TALENTO] DK  [Ravenous Dead] Buggo

### ISSUE THREAD

**Issue by Harlokk** [AzerothShard/AzerothShard-Issues-ita#32]
il talento in questione  [Ravenous Dead] dovrebbe donare al ghoul il 60 % di str del DK, tutta via non avviene così ma gli da un pò meno del 60 %.

Dk str: 2563
Ghoul str: 2072
[Ravenous Dead] Bonus str 60% :       60:100 = X:2563 -> X=(60*2563)/100= 1537,8
[Ravenous Dead] Bonus str 60%: = 1537,8

Ghoul str teorico : 2072 + 1537,8 = 3609,8

Ghoul str effettivo: 3201

Lascio in allegato le screen:
la str del dk nelle due screen è diversa perchè [Ravenous Dead] dona anche al dk 3% di str in più

![wowscrnshot_072416_174010](https://cloud.githubusercontent.com/assets/13575586/17085375/917df838-51d6-11e6-9852-5cfb21e1a207.jpg)
![wowscrnshot_072416_174014](https://cloud.githubusercontent.com/assets/13575586/17085376/917f6c18-51d6-11e6-9bac-91a51286213a.jpg)
![wowscrnshot_072416_173857](https://cloud.githubusercontent.com/assets/13575586/17085379/982df778-51d6-11e6-9745-7a3c47d4da83.jpg)
![wowscrnshot_072416_173914](https://cloud.githubusercontent.com/assets/13575586/17085378/982772b8-51d6-11e6-996c-0d37395f1f35.jpg)

**Comment by mik1893** [comment]
non e' affatto buggo, e giusto cosi - hai interpretato male il talento:

Increases your total Strength by 3% and the contribution your Ghouls get from your Strength and Stamina by 60%

La contribution che il ghoul prende dalla strenght e dalla stamina, e' il fattore moltiplicativo che viene applicato alla strenght del dk, NON una percentuale della strenght del DK.
Da WoWWiki:

http://wowwiki.wikia.com/wiki/Risen_Ghoul

Ghouls receive 70% of their master's strength untalented and 112% of their master's strength fully talented with 3/3 Ravenous Dead. A Glyph of the Ghoul causes ghouls to inherit an additional 40% of their master's strength, for a maximum strength inheritance of 152%.

perche il 60% della contribution (che e' il 70%), e il 42%. Quindi la strenght aumenta del 42% diventando 112%.

La strenght con solo quel talento dovrebbe essere 2563*1.12 = 2870, non 3000+.

E' BUGGO IN POSITIVO.
