### ISSUE TITLE
[DK] Gargoyle, problema target

### ISSUE THREAD

**Issue by Ualock** [AzerothShard/AzerothShard-Issues-ita#33]
Segnalato anche nel vecchio core, ho fatto un test veloce e sembra che anche su nuovo core persista questo fastidioso bug.
Il gargoyle deve attaccare il target sul quale mando il ghoul, mentre continua ad attaccare il primissimo target sul quale è stato summonato/mandato.

http://www.skill-capped.com/forums/showthread.php?1235-Macro-For-gargoyle-switch

#showtooltip Summon Gargoyle
/cast Summon Gargoyle
/petstay
/petattack

This summons the gargoyle and makes the gargoyle attack your target (modifiers can be added OFC), since **# the gargoyle and the ghoul are "linked"** this OFC also makes the ghoul attack the target you can add this in the end

**Comment by Ualock** [comment]
grazie mik1893 per aver visionato la segnalazione, penso pero' che la priorità di questo fix sia alta, in quanto è un **grave** handicap per il dk in arena

**Comment by mik1893** [comment]
fixato in anticipo, su milestone 1.0
