### ISSUE TITLE
Judgement

### ISSUE THREAD

**Issue by Cuthbertx** [AzerothShard/AzerothShard-Issues-ita#36]
La spell Judgement (tutte le versioni) del Paladin non funziona come dovrebbe. Anziche' essere castata su target in range a prescindere dalla posizione del Paladin, questa viene castata se e solo se il Paladin ha di fronte il target.

Per verificare il bug basta un duel, mettersi di spalle nelle vicinanze dell'avversario e castare Judgement.
Si vedra' chiaramente che questa spell non parte, come invece dovrebbe.

**Comment by mik1893** [comment]
fixato - disponibile dal prossimo recompile del main
