### ISSUE TITLE
Hand of Reckoning

### ISSUE THREAD

**Issue by Cuthbertx** [AzerothShard/AzerothShard-Issues-ita#37]
Il taunt del Paladin, la Hand of Reckoning, da' come risultato "immune" se castato su player avversario.

Questa spell viene utilizzata per rimanere in combat e lasciare in combat il target a distanza (esempio: rogue in lontananza che sta scappando per tornare in stealth).

La meccanica giusta vorrebbe che la spell entrasse, aggiungendo anche un debuff di breve durata.

Su pet vari inoltre (succube, ghoul, fel, elementali) dovrebbe pure fare danno nel caso in cui il pet stesso non stia targettando il Paladin. Bisogna verificare se cio' avviene

**Comment by mik1893** [comment]
http://wowwiki.wikia.com/wiki/Hand_of_Reckoning

WoW Icon 16x16 Hotfix (2009-08-08): "Hand of Reckoning is no longer able to be used on targets that are immune to taunt, including players." 

chiuso
