### ISSUE TITLE
 Deathbringer's Will & off hand

### ISSUE THREAD

**Issue by xlollomanx** [AzerothShard/AzerothShard-Issues-ita#39]
Quando procca il dbw http://wotlk.openwow.com/item=50363 , accade che l' off hand del war sparisce (ma credo anche per tutte le altre classi che usano 2 armi a 1 mano), premetto è un bug visivo e il danno dell' arma è comunque presente, ma lo ritengo piuttosto fastidioso.

**Comment by Irome** [comment]
Questo bug grafico è sempre esistito, anche sui server ufficiali della Blizzard. Non è un problema riguardante il core, quindi non è fixabile.

Questo video da la conferma:

https://www.youtube.com/watch?v=EwxFnJ1r9I0
