### ISSUE TITLE
Greater Blessing Shares

### ISSUE THREAD

**Issue by Cuthbertx** [AzerothShard/AzerothShard-Issues-ita#40]
In fase di preparation BG (e credo anche arena) i Greater Blessings del Paladin (Kings, Wisdom, Might, Sanctuary) sono erroneamente "condivisi" fra player classes e pet di altre classi.

Ad esempio, in un Eye of the Storm, un Blessing of Might fatto su un Rogue e' finito anche sul Ghoul del DK che gli stava di fianco, e viceversa.

Spesso capita di verificare situazioni analoghe nelle piu' svariate combinazioni classe / pet di altra classe.

**Comment by mik1893** [comment]
fixato

**Comment by Cuthbertx** [comment]
I pet continuano a sharare Blessing erroneamente, non e' stato fixato
