### ISSUE TITLE
Danno Warrior Fury esageratamente basso

### ISSUE THREAD

**Issue by Dozzle** [AzerothShard/AzerothShard-Issues-ita#42]
Salve, ho fatto dei test sul danno del warrior fury e ho riscontrato una diminuzione esagerata e sproporzionata rispetto alle stats che possiedo.
Con tutti i proc (doppio trinket endgame 277 (dbw) e 284 (sharpened), doppio berserking, proc anello ashen verdict 277, raziale dell'orco blood fury, e 9 anime attive della mourne) di bianco il massimo crittato è stato 3.7k su un mob con 67k di vita ad icecrown, cioè la metà del mio attack power (proc esclusi), quindi teoricamente impossibile! Il massimo crittato di spell invece è stato 10k, su 11k di attack power che avevo in quel preciso istante, avrei dovuto quindi crittare almeno il doppio!
Su quello stesso mob, stessi proc, stesse stats di base, sul vecchio core di bianco crittavo almeno 8k e di crit con spell oltre 17-18k.
Senza nulla togliere al grande lavoro che state facendo, agli sforzi e alla grande pazienza che portate, su altri server in cui il warrior è fixato offylike, stessa patch, sullo stesso mob, a parità di condizioni e stats, i danni che faccio sono ancora più elevati.
Per quanto riguarda i talenti, attualmente non rilevo alcun bug, almeno in spec fury, quindi mi riservo di aprire altri issue per segnalare eventuali bug anche su spec Arms pvp, Arms pve e Protection, al fine di migliorare l'esperienza di gioco di tutti gli utenti che usano la mia stessa classe e di rendere AS un server quanto più vicino possibile alla perfezione.

**Comment by mik1893** [comment]
mancano i conti - devi fare i conti di quando deve essere il danno, mettendo giu i talenti che hai.
del tipo:

PG blablabal  -    2300 strenght - talenti attivi che aumentano il danno bianco 1, 2,3, che aumentano di 20,30,40% ild anno.
Danno effettuato: 10
danno atteso: 11

si attiva il trinket blablabla

vedrai, e ne sono certo perche lo abbiamo testato, che i calcoli saranno tutti giusti.
semplicemente prima il war fury era buggo in positivo e faceva i mega danni, per via di stack sbagliati di diverse spell. Per cui la tua esperienza precedente poteva essere alterata da questo

**Comment by xlollomanx** [comment]
Il danno bianco che hai tu io non l'ho notato... ho girato un po per icecrown a cercare mob e ho visto che crittavo circa 7k abbondanti con praticamente niente proccato. Prova resettare spec, switcharla toglierti tutto l' equip e rimetterlo.

**Comment by mik1893** [comment]
@xlollomanx , per favore, se riesci a organizzare dei test piu precisi, ma a sentire in generale il fury sembra funzionare bene. Nel caso, vanno fatti i test specifici... e aprire ticket relativo al problema singolo (non al danno generale soggettivo riportato)
