### ISSUE TITLE
Argent Guntling

### ISSUE THREAD

**Issue by Roazar** [AzerothShard/AzerothShard-Issues-ita#43]
Per chi non lo sapesse questo e' il pet che completando l'apprendistato con l'argent tournament
prima questo pet vendeva reagenti e roba da mangiare (molto utile in raid) ma adesso non apre la schermata di vendita e acquisto

**Comment by mik1893** [comment]
ho provato e se si ha l achievement http://www.wowhead.com/achievement=3736/pony-up funziona... qualcuno puo ritestare per favore e vedere se corretto? @Arkan0r  ?

**Comment by ghost1988** [comment]
Confermo come da offy all'inizio è un companion prendendo la cavalcatura e l'achievement ha "un'evoluzione" e diventa un vendor (offylike)
