### ISSUE TITLE
Proc trinket e danni delle spell

### ISSUE THREAD

**Issue by Ualock** [AzerothShard/AzerothShard-Issues-ita#5]
salve, ho fatto un giretto nel nuovo core e sono andato a testare il mio pg al manichino, è sorto un problema sui danni , ve lo spiego subito: Casto corruption, che fa diciamo 1800 a tick, proccano i trinket con spell power e i tick di corruption fanno sempre 1800. Refresho la spell con i trinket ancora proccati e il damage cambia a 2500, l'effetto dei trinket finisce e il damage resta ancora 2500. Il problema è il seguente: il danno delle spell non tiene conto dello spell power in tempo reale ma usa delle istantanee delle stat e le attribuisce alle spell e anche quando le stat cambiano il damage rimane invariato, spero di esser stato il più chiaro possibile

**Comment by Yehonal** [comment]
I test sono da effettuare su pg non sui manichini.
Il 06/Lug/2016 03:36, "Ualock" <notifications@github.com> ha scritto:

**Comment by Ualock** [comment]
i test li ho effettuati su pg e il risultato non cambia, i dot devono calcolare lo spell power in tempo reale, non a snapshot, è un bug sia positivo che negativo, in quanto se ho dei proc e faccio dot all'ultimo secondo, il dot beneficia per tutta la sua durata dello spell power che non ho più, per contro se ho appena messo dei dot sul target e mi proccano i trinket questi faranno il damage iniziale per tutta la durata del proc rendendo il proc praticamente inutile

**Comment by Ualock** [comment]
p.s. test effettuati anche sul core attuale e il risultato non cambia anche con altre classi e dot tipo rend del warrior.

**Comment by Yehonal** [comment]
@mik1893 interessante direi

**Comment by mik1893** [comment]
E esattamente l opposto. In wow, I danni di una spell sono snapshottati al momento del cast. Ne abbiamo parlato anche in chat trovando diversi articoli e referenze. De facto, e il bug più storico di trinitycore. Il fatto che vengano snapshottati fa si che il dps di un personaggio dipenda dalla skill e non random - vanno castati e refreshati i dot non solo seguendo la rotazione ma anche i proc
