### ISSUE TITLE
chain heal shammo BUGGO

### ISSUE THREAD

**Issue by magicdead** [AzerothShard/AzerothShard-Issues-ita#51]
Save GM 
ieri sera mentre facevo raid ho riscontrato un bug, il bug in questione è la  chain heal (http://wotlk.openwow.com/spell=55459) ossia non "jumpa" sui 3 taget vicini/successivi(o 4 se è glifato) INDIPENDENTEMENTE dalla razza del personaggio e/o dal party.
 Questi di seguito sono due esempi di bug:
1) lo fa solo su se stessi se non si targetta nessuno http://prnt.sc/c0q0ro, invece la spel dovrebbe andare sui player vicini(enemy target)
 2) se si targetta il bersaglio  la casta SOLO sul il bersaglio http://prnt.sc/c0q1d3 (ci sono vicini altri 2 player)
penso che sia un grosso problema con lo shammo, risolvetelo il prima possibile.

dimenticavo questo è lo screen con il party http://prnt.sc/c0q83k

**Comment by mik1893** [comment]
fixato, attivo dal prossimo passaggio fix sul main
