### ISSUE TITLE
WARLOCK - Check calcolo danni spell

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#52]
Ho iniziato a testarmi ogni singola spell del lokko in seguito a varie cose che non mi convincevano molto ed ho deciso di prendere come prima spell l'incinerate. A voi i calcoli in base ai codici del db della blizzard dati da un dev. 
[CALCOLI.xlsx](https://github.com/AzerothShard/AzerothShard-Issues-ita/files/397955/CALCOLI.xlsx)

EDIT (from mik1893):
- aggiorniamo con commenti quali sono le formule utilizzate che prendiamo dal dbc + coefficienti e segnamo se i risultati sono in linea

**Comment by mik1893** [comment]
sembra che manchi il coefficiente livello del danno - ci guardo dentro

**Comment by mik1893** [comment]
Incinerate: Danno base = 582 - 677 + 71,43% SP + talenti.   -- OK (ulteriori test su talenti?)

**Comment by Irome** [comment]
Questo report risale al vecchio core, cioè trinitycore.
