### ISSUE TITLE
Metropolitana Stormwind/Ironforge

### ISSUE THREAD

**Issue by Irome** [AzerothShard/AzerothShard-Issues-ita#54]
Ho provato a prendere il tram a stormwind per andare ad ironforge, e mi sono accorto che durante il tragitto prima di arrivare ad ironforge, il tram senza fermarsi torna indietro e quindi non da la possibilità di arrivare a destinazione. Ci ho provato tantissime volte ma il problema rimane.

http://www.wowhead.com/zone=2257/deeprun-tram

**Comment by ghost1988** [comment]
Appena provato, si ferma e lascia scendere Iron>storm

**Comment by Irome** [comment]
Si da ironforge a stormwind funziona, ma se provi da storm ad iron ti fa tornare indietro prima di arrivare.

**Comment by Ercules76** [comment]
Ho provato più volte da Storm -> Iron e da Iron -> Storm, sono sempre arrivato a destinazione, potresti riprovare in game appena puoi?
