### ISSUE TITLE
Bug grafico - Fake GS

### ISSUE THREAD

**Issue by Irome** [AzerothShard/AzerothShard-Issues-ita#56]
Guardando la gente che ha applicato il transmogrification sul proprio equip, mi son reso conto che il GS è alterato, ad esempio se un pg ha un equip da 6.5k di gs con un transmog magati TBC, il suo gs scende 3/3.5k. Penso quindi che il problema è il transmogrification.

Può sembrare una sciocchezza ma in game questo Fake può dare problemi hai players, per esempio se vengono scelti in base al GS per fare raid.

**Comment by xlollomanx** [comment]
Premetto che io non uso più GS e questa cosa mi è già capitata. Probabilmente l' addon vede l' equip che è usato come trasmog e non quello effettivo. Non credo sia fixabile questa cosa, comunque ricordo che se lasciavi un attimo lavorare l' addon poi segnava il gs giusto

**Comment by mik1893** [comment]
il transmogrifier non e' una feature originale di 3.3.5 per cui gli addon non sono studiati per supportarla.
l addon gearscore guarda il display ID dell item per generare il gearscore, temo - questa cosa non e' fixabile, se non sul addon, lato codice server non possiamo fare assolutamente niente
