### ISSUE TITLE
Quest First Aid: Triage

### ISSUE THREAD

**Issue by Irome** [AzerothShard/AzerothShard-Issues-ita#57]
La quest per il First Aid a Dustwallow Marsh è bugga. Quando si deve curare il paziente morente con la [Triage Bandage] non si ha il tempo necessario per curarlo, il tempo per castare la spell è più lunga del tempo di spawn e nella morte del paziente, questo quindi fa fallire la quest e non da la possibilità di completarla.

http://www.wowhead.com/quest=6624/triage#see-also

**Comment by DantestyleXD** [comment]
Completata senza alcun problema di tempo, ti consiglio di posizionare la telecamera in modo da poter vedere l'intera stanza e di avere un "punta e clicca" pronto su ogni paziente.
