### ISSUE TITLE
[DK] Gargoyle Casta in Turn Evil

### ISSUE THREAD

**Issue by Cuthbertx** [AzerothShard/AzerothShard-Issues-ita#58]
Il Gargoyle continua a castare anche se gli viene fatta spell del Paladin Turn Evil, da verificare se cio' avviene con altri CC, in primis Shackle del prete e Holy Wrath sempre del Paladin.

**Comment by mik1893** [comment]
Nota dev; controllato nel codice e il controllo sullo UNIT_STATE_CONTROLLED c'e - va messo in debug

**Comment by mik1893** [comment]
fixato, sara up da domani o dopodomani sul main server.
per sicurezza ho aggiunto tutti  i casi - FEAR, CONFUSE, STUN, etc etc etc
