### ISSUE TITLE
tempo castting time conflagate

### ISSUE THREAD

**Issue by magicdead** [AzerothShard/AzerothShard-Issues-ita#6]
Salve popolo di AS
ho notato sul il nuovo server  che la spell conflagate funziona e non funziona,mi spiego meglio, all'inizio dove si creano i pg la spell funziona correttamente, in altri posti no(tipo manichini di orggrimar e undecity,mob sotto daran) non solo, ma ha anche un ritardo di un 1 sec di cast sulla spell(10 sec di base,invece ne fa 11 sec) che non funge.
Questi seguenti esempi sono la conferma:
1) http://prnt.sc/bpijak questo è nella parte dove si crea il pg( ovviamente è senza equip, spell rank1 immolate)
2) http://prnt.sc/bpim4g qui è il manichino di orgrimmar e come con l'immolate di rank 11 e non funge
3) http://prnt.sc/bpiok3 qua è sotto dalaran e non funziona
4) http://prnt.sc/bpipzj sempre sotto dalaran e non funziona
5) http://prnt.sc/bpiri1 qui è a silvermoon (ovviamente senza equip e rank immolate 1) e non funge
6) http://prnt.sc/bpitws sempre vicino silvermoon e funziona (ovviamente senza equip e rank immolate 1)
7) http://prntscr.com/bpivty manichino di undercity non funziona

In conclusione su alcuni mob o manichini funziona correttamente e su altri no
scusate se sono stato ripetitvo in alcuni scrren XD

**Comment by Yehonal** [comment]
Grazie per la segnalazione e per gli screen :D daremo un occhiata

**Comment by mik1893** [comment]
credo sia dovuto al fatto che  hanno fixato il behaviour del conflagrate in pvp con un sistema custom.
Su offy, il conflagrate aveva una particolare dinamica che inseriva un ritardo microscopico fra immolate e conflagrate.. Era un "bug" su offy, ma era diventato parte del gioco 
http://eu.battle.net/wow/en/forum/topic/2723297471

**Comment by magicdead** [comment]
ho letto il post http://eu.battle.net/wow/en/forum/topic/2723297471 e tanti altri commenti , mi sembra strano ch'è dalla blizzard che risale questo problema anche prima della wotlk, non sto dicendo che non è vero, e come se fosse "fix/bug" allo stesso tempo.,se sarà cosi la vedo molto ma molto difficile giocare il destro in pvp, perchè come scritto nel topic c'è quel "microtempo" prima che si casti il conflagate. Questo "pseudo-problema"  e possibile, SE SARA NECESSARIO, modificargli la sua scrittura o il suo codice?
Come scritto anche nel topic... "fa parte del gioco ed è molto fastidioso"

**Comment by mik1893** [comment]
il problema e' che non e' controllabile, e' dovuto a come funziona il server di wow.
In ogni caso, prima che si attivi il conflagrate deve:

arrivare il cast di immolate al server - effettuare il primo tick - tornare indietro.

Se hai 100 ms di ping, sta cosa avverra nel giro di 300 ms circa. Per cui non e' mai istantaneo

**Comment by magicdead** [comment]
Penso che sia impossibile controllare un "diffetto" del genere sul il database.
Ovviamente non sarà mai istantaneo ma dipenderà,a volte,anche dalla connessione del server di wow tra client/server,
Certamente ,quando casto immolate avrà :
 - un tempo di cast al target
- un tempo di tick istantaneo, ma quest'ultimo la sua  lettura da parte del server, è molto veloce.

**Comment by mik1893** [comment]
si, e come ho gia spiegato diverse volte nei vari server di wow in cui ho fixato (perche e' una roba che si presenta ogni volta), non e' un bug ne qualcosa che si puo controllare. 
E' dovuto a come funziona wow, specificatamente a come reagisce il client di wow sul conflagrate, quando gli arriva il pacchetto attivazione del cast dal server. E' delayato, sia per via della lag fra server e client (il pacchetto fa 2 volte il giro server client, quindi 4x lag), sia per via di come viene gestito internamente dal client,, ed e' appunto una cosa che c era anche su offy e NON si riesce a risolvere, in alcun modo.

**Comment by magicdead** [comment]
non ti sto dando torto su quello che hai scritto, ti ho solo detto che per me è strano vedere questo "difetto"
