### ISSUE TITLE
[DK] Gnaw, problema range

### ISSUE THREAD

**Issue by Ualock** [AzerothShard/AzerothShard-Issues-ita#62]
Salve vorrei segnalare un bug del ghoul del dk. Quando il pet è in melee range e pronto per stunnare non riesce ad arrivare al target, si ferma un paio di yard prima nonostante si spammi la spell gnaw, come se considerasse una hit box più larga del normale e quindi non arriva al centro di quest'ultima per stunnare l'avversario.
La spell è funzionante solo quando si usa Leap che lancia il ghoul alle spalle del nemico e subito dopo si usa gnaw o se l'avversario corre nel senso opposto del ghoul quindi incrociandosi si trova abbastanza vicino per usare gnaw.
Per riprodurre il bug fare duel con un qualsiasi avversario, mandare il ghoul sul nemico /petattack e provare a spammare gnaw. Inutile dire che in arena avere questo ghoul che insegue il target e non riesce a stunnarlo al momento giusto è un grosso handicap per il timing dei CC.
Grazie mille

**Comment by Ualock** [comment]
Edit: ad inizio duel neanche Claw (l'abilità che fa damage) del ghoul riesce ad arrivare al target, a meno che il nemico non si avvicini al ghoul. In questo caso si trova in range e può usare la spell. Ho notato che se il ghoul riesce a colpire la prima volta il target, il range si fixa per così dire e il ghoul può usare tutte le abilità, ma non appena il target si allontana e da un distacco di qualche yard al ghoul questo nuovamente ha problemi ad entrare in range utile.

**Comment by mik1893** [comment]
e dovuto al commit per il cast delle spell dei ept che li mette in movimento - ci do un occhiata asap

**Comment by Ualock** [comment]
ciao mik, novità? sto bug è **pesantissimo** soprattuto in arena non si riesce a fare cc al momento giusto!!

**Comment by Ualock** [comment]
up, novità?
