### ISSUE TITLE
HUNTER BUG disarm

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#67]
Ciao volevo comunicare un bug dell hunter.
usando il disarm con lo scorpid sting non funziona o meglio. disarma una volta se si usa il readiness per azzerare i cd non viene azzerato il cd interno di un minuto necessario per il secondo disarm . non viene nemmeno refreshato lo sting chiedo fix.
aggiungo un accuratezza.
se si usa il readiness per disarmare 2 volte in teoria una volta finito uno dovrebbe iniziare l altro senza aspettare la fine per poterlo sparare e disarmarlo come funzionava sul vecchio core. grazie dell attenzione. saluti marie

**Comment by mik1893** [comment]
non sono sicuro che su wotlk, due auree con durata castate una dopo l altra possano "sommare" la durata - andrebbe verificato se e' una dinamica particolare.
Per il cooldown interno del disarm controllo!

**Comment by Fabrisiu** [comment]
il readiness dell hunter resetta tutti i cd dell hunter tranne bw . resetta anche il minuto necessario a fare d nuovo il disarm. ecco per cosa intendo consecutivo.

________________________________
Da: mik1893 <notifications@github.com>
Inviato: giovedì 11 agosto 2016 11.20
A: AzerothShard/AzerothShard-Issues-ita
Cc: Fabrisiu; Author
Oggetto: Re: [AzerothShard/AzerothShard-Issues-ita] HUNTER BUG disarm (#67)


non sono sicuro che su wotlk, due auree con durata castate una dopo l altra possano "sommare" la durata - andrebbe verificato se e' una dinamica particolare.
Per il cooldown interno del disarm controllo!

-

**Comment by mik1893** [comment]
ciao, trovato il problema. Il cooldown sul disarm viene aggiunto non direttamente dalla spell ma manualmente da uno script e non viene letto dal comando di rimozione cooldowns

Fixato, sara' disponibile dalla prossima compilazione del main
Grazie per la segnalazione!
