### ISSUE TITLE
Hunter bug Deterrance

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#68]
se si usa il deterrance + revive pet il warrior insieme al rog riescono a interrompere il cast alias ress oltrepassando il deterrance è un bug. chiedo fix.
Marie

**Comment by xlollomanx** [comment]
Almeno per quanto riguarda il war non è un bug è normale. L' overpower è fatto apposta per bypassare difese come il deterrance. Comunque https://github.com/TrinityCore/TrinityCore/issues/6919

**Comment by Fabrisiu** [comment]
non riesco a postarti il video. ma guardati questo è lo stesso bug.
https://www.youtube.com/watch?v=7TaCO-C0VGk

**Comment by mik1893** [comment]
Non e un bug, il deterrence DEVE venire oltrepassato da tutte le abilita linkate nel topic del rogue
