### ISSUE TITLE
hunter vs dk antimagic bug op

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#71]
Salve vi scrivo in merito a un bug dell hunter vs dk .
il dk in antimagic shield non prende nè il serpent sting nè lo scorpid sting se si usa il kimera con lo sting ( lo si mette prima dell antimagic ) il danno è praticamente 0 e dice immune.
dovrebbe disarmarlo e mettere lo sting in antimagic sia scorpid che serpent non dovrebbe critta d conseguenza non si ha il daze, non dovrebbe crittare ma prendere pochi danni. ma il fatto che prenda 0 danni è troppo op. richiedo fix.
marie

**Comment by xlollomanx** [comment]
Se non sbaglio il serpet fa danno natura e l' antimagic shield (improvato da unholy) dovrebbe rendere immune a tutte le classi di danno magico per tutta la sua durata.

**Comment by mik1893** [comment]
Non e un bug. Hai citato due spell dell hunter che fanno danno nature e l antimagic shield improvato le cancella rendendosi immune
