### ISSUE TITLE
bug hunter pet bg

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#74]
ho notato che nei bg a volte i pet se vengono chillati e nn ressati nn appaiono più nemmeno col fischetto.
richiedo fix

**Comment by mik1893** [comment]
lo specifico problema nel BG dovrebbe essere fixato dal prossimo giro di fix sul main server, ma e' relativo al problema generico col salvataggio dati pet su linux, sul quale stiamo lavorando.
Tengo aperto per sicurezza

**Comment by Irome** [comment]
Il bug è stato verificato e risolto.

Chiudo la issue.
