### ISSUE TITLE
leggero desync mvimento scattershot client-server (old same story)

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#76]
salve vi scrivo in merito a un bug se vi si fa lo scatter contro un avversario in movimento vi è un bug grafico il quale sposta l avversario visivamente km lontano da dove si è fatto lo scatter rendendo impossibile poter usare questo controllo. richiedo un fix poichè è grave visto che ha a che fare con la meccanica del pg. inoltre le trap specialmente la freezing dovrebbe essere istantanea qui invece si perdono 2-3 secondi e a volte non va proprio ( nonostante si abbia 125 di spell pene ) 
saluti
Marie

**Comment by magicdead** [comment]
le trappole sono giuste e il loro tempo di attivazione ed è giusto ,hanno un loro cd interno che è di 2-3, questo "timeing" or "arming time" c'era anche su offy tbc

**Comment by Fabrisiu** [comment]
hai provato a fare scatter più trap mentre l avversario è in movimento? prova a farlo e dimmi avrei dei dubbi sulla freezing arrow ... sai com'è dovrebbe essere istantanea o almeno su offy era cosi ;) e poi stiamo su wotlk non tbc.

**Comment by magicdead** [comment]
1)il delay delle trappole e stato spostato da tbc offy a woltk offy...
2) se ti mostro un video, in tbc, in cui faccio quello in cui ha iscritto tu... prendo il perma ban per pubblicità occulta....
3) se ne sei sicuro vai sul il core di trinity ce cerca delay trap o timing trap o qualcosa de genere... e troverai solo fix di trappole che scattano dopo 2-3 secondi...

**Comment by Ercules76** [comment]
Non fate paragoni tra offy e 3.3.5, molte meccaniche sono state cambiate, dovete fare riferimento sempre a informazioni riguardanti la nostra patch

**Comment by mik1893** [comment]
il delay time delle trappole e' un settaggio presente nel core, e dipende dalla trappola, diverse trappole hanno settaggi diversi.
I valori vengono presi dai DBC del client wow, quindi a meno di hotfix (documentabili tramite wowwiki) dovrebbero essere 100% corretti.
Ho giocato hunter per tutta tbc e wotlk, su offy, e l arming time delle trappole e' sempre esistito, si e' modificato col tempo. 
Il problema a cui tu fai riferimento comunque non c entra niente con l arming time. E' il problema dello scatter shot che esiste su TUTTI gli emulatori di wow dall'alba dell esistenza dell emulazione di questo gioco. Lo scatter shot genera un movimento di tipo confuse, che viene eseguito lato client in maniera diversa da come viene eseguito lato server: in pratica e' una desincronizzazione - tu vedi l avversario da una parte, mentre l avversario probabilmente e' LEGGERMENTE spostato, sul server. questa particolare desincronizzazione si e' rilevata quasi impossibile da fixare perche dovuta a come il client di wow genera il movimento di tipo confuse specifico dello scatter shot. Per questo, alcune volte, lo scatter + trap non funziona come dovrebbe. 
Se cerchi scatter shot trinitycore, su google, ti usciranno 200 topic a riguardo

**Comment by Irome** [comment]
Questi video dimostrano il corretto funzionamento delle spells:

Scatter: http://tinypic.com/player.php?v=24vp82u%3E&s=9#.WGf3U6nry1k
Freezing: http://tinypic.com/player.php?v=x6fynd%3E&s=9#.WGf3eKnry1k
