### ISSUE TITLE
TALENTO BUG HUNTER FOCUSED AIM

### ISSUE THREAD

**Issue by Fabrisiu** [AzerothShard/AzerothShard-Issues-ita#77]
salve vi scrivo in merito a un talento buggo dell hunter.
questo talento in teoria darebbe il 3% di hit e il 100% di castare lo steady senza interruzioni anche subendo danni. ho dei dubbi sia con l % di hit( che è inesistente secondo test ).
e il cast dello steady viene interrotto o c impiega + danno quando si subiscono danni. richiedo fix.
Saluti .
Marie

**Comment by mik1893** [comment]
secondo test quale? riporta cifre per favore!
Apprezzo enormente lo sforzo di reportare i problemi, ma abbiamo bisogno di piu dettagli.
Ho provato ora su un pg creato e talentato da zero, e il talento funziona correttamente.

La % di hit e' stata testata la settimana scorsa ed e' stata applicata una lieve correzione, ma in generale il calcolo e' corretto al netto di arrotondamenti. Come hai fatto a testate la hit? stai testando sul manichino? Il manichino NON PRENDE meta' dei talenti applicatovi (per via della sua natura di dummy).
Dacci  piu dettagli!

**Comment by Irome** [comment]
Il talento è stato testato e risulta funzionante.
