### ISSUE TITLE
Il mio pg (Worlas) è buggato

### ISSUE THREAD

**Issue by Aspire03** [AzerothShard/AzerothShard-Issues-ita#78]
Non posso castare Conflagate immediatamente dopo aver castato Immolate. Riesco a farlo dopo un breve ma comunque anomalo lasso di tempo. Il pg buggato si chiama Worlas

**Comment by Ualock** [comment]
non è bug, "l'anomalo lasso di tempo" è il corretto funzionamento della spell, come da ufficiale

**Comment by mik1893** [comment]
abbiamo gia trattato l argomento diverse volte, ed e gia stato creato un topic a rigaurdo con tutti i link relativi al comportamento di questa spell.
http://eu.battle.net/forums/en/wow/topic/2723297471
