### ISSUE TITLE
bug sull' enchant del cloak/back da Tailoring 420, "Swordguard Embroidery"

### ISSUE THREAD

**Issue by elegias** [AzerothShard/AzerothShard-Issues-ita#81]
buonasera.
l'enchant in oggetto che si unisce al cloack o back dello stesso tailorer( nel mio caso warrior fury), che si raggiunge con Tailoring a 420 di spell,  dovrebbe portare un buff bonus di 400 attack power per 15 secondi .
L'attivazione invece del buff, provata con l'addon POWA, avvisa che invece aggiunge bonus di attack power di 480 per 10 secondi. 
La differenza si traduce, secondo me in modo non conveniente con 480x10sec anziche' 400x15sec, con secondo me la differenza di 80 punti in piu'x 10 sec.( 80 x10=800) anzichè 400x5 sec (2000 punti di ATTPOW).
Ovvero ora il buff da un bonus totale di 4800 punti bonus di AtPow in 10 sec. anzichè 6000 in 15 sec.
Secondo me andrebbe fixato all'originale del buff previsto dal gioco(appare scritta originale in inglese quando parte).
scusate grazie. se potete mandarmi risposta in game, via mailgame, vi ringrazio.

**Comment by mik1893** [comment]
Ciao, 
nei dbc di wow segna durata 15 secondi e attack power 400 - e senza usare addon vedo lo stesso.
Per cui non e' un bug, e l addon che stai dicendo che fa un calcolo completamente a caso.

In game, l enchant da correttamente 400 ap per 15 secondi.

**Comment by DantestyleXD** [comment]
3.2.0 (04-Aug-2009): Changed to chance to increase attack power by 400 from prior value 300.
3.0.2 (14-Oct-2008): Added.

**Comment by Arkan0r** [comment]
Appena testato, confermo ciò che dice Mik, al momento del proc dura 15 secondi e l' attack power aumenta di 400, fai dei test senza addon e vedrai che l' enchant funziona correttamente

**Comment by elegias** [comment]
grazie mille, soprattutto per la pronta risposta.
con stima.
ele

2016-08-15 11:35 GMT+02:00 Arkan0r <notifications@github.com>:

**Comment by elegias** [comment]
grazie della pronta risposta.
verifico l'addon, senza dubbio, ma cmq grazie.
ele

2016-08-15 11:17 GMT+02:00 mik1893 <notifications@github.com>:
