### ISSUE TITLE
Arene - Rating strano

### ISSUE THREAD

**Issue by Attrito** [AzerothShard/AzerothShard-Issues-ita#83]
Parliamo di arene

Su offi guadagni 10 di media su ogni vittoria e perdi 10 di media su ogni sconfitta
Su azeroth shard guadagni 20 di media su ogni vittoria e perdi 8 di media su ogni sconfitta
C'è qualche cosa che non va , vedo gente che ha 70 wins e 60 lost con 1400 di arena rating

Esempio team : W gli anni novanta

**Comment by mik1893** [comment]
e' semplicemente l algoritmo settato a questa maniera, per facilitare il farming dei punti arena ed equilibrare il gioco. Su offy giocano 2000+ player per server, su azeroth shard 200.
I piu forti fanno comunque rating piu velocemente, ma i piu deboli giocando hanno comunque la possibilita di salire un po di rating.
