### ISSUE TITLE
Bug dispel felhunter

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#84]
http://www.wowhead.com/spell=212465/devour-magic

La suddetta spell dovrebbe dispellare i magic effect ma non lo fa. Testando su un priest con tutti i vari buff up e proc esce fuori l'errore "nothing to dispel".

**Comment by ShinDarth** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/67

**Comment by Thurin93** [comment]
#https://github.com/azerothcore/azerothcore-wotlk/issues/67
Fixata e Chiusa.
