### ISSUE TITLE
Barra Fatigue nelle pozze d'acqua

### ISSUE THREAD

**Issue by DantestyleXD** [AzerothShard/AzerothShard-Issues-ita#87]
In fase di test, mi sono trovato a camminare nelle pozze di alcune regioni, in particolare Zangarmarsh e Sholazar Basin, e mi sono imbattuto nella barra fatigue camminando a random dentro la pozza.

Inoltre, a Zangarmarsh, ci sono punti dove si beccano 600 danni al secondo totalmente a random sempre camminando nelle pozze.

I danni sono irregolari poichè, tale comportamento nei liquidi, dovrebbe verificarsi solo se cammino nella lava o acido...non nell'acqua.

Il problema l'ho verificato in local con la repo di AzerothCore, quindi chiedo conferma del bug anche sul live.

Allego immagini.
https://dl.dropbox.com/s/870hvkady2b195c/WoWScrnShot_081816_214846.jpg
https://dl.dropbox.com/s/gsm92rg9srx5rn8/WoWScrnShot_081816_220937.jpg
---

Server: Local (Repo AzerothCore)
Last commit hash tested: 3761e9d8433f4d031b3477b787134a1d868a8971
O.S.: Windows 10
Compiler: MS Visual Studio 2013

**Comment by Deteroch** [comment]
Ciao, ho controllato personalmente in entrambe le zone che tu hai riportato nelle immagini(ci ho voluto un po' per trovarle soprattutto quella a Sholazar) e ti posso dire che nel server principale non ho riscontrato nessuno di quei comportamenti "anomali". Ho nuotato in lungo e largo e camminato ma non ho preso ne danni ne sono entrato in fatigue!
