### ISSUE TITLE
[quest] Going Bearback (son of hodir chain)

### ISSUE THREAD

**Issue by Hollvedel** [AzerothShard/AzerothShard-Issues-ita#88]
Nella quest bisogna uccidere Frost Giant e Frostworg su un veicolo-orso.
Il problema è semplice: i nemici sono friendly e non possono essere feriti in alcun modo.

**Comment by mik1893** [comment]
gia aperto 
https://github.com/AzerothShard/AzerothShard-Issues-ita/issues/80

grazie comunque per il report!
