### ISSUE TITLE
Utgard Pinnacle -Recipe Scheletri-

### ISSUE THREAD

**Issue by Unreal899** [AzerothShard/AzerothShard-Issues-ita#9]
Come da titolo i primi add dell'istance dovrebbero droppare recipe che non droppano, provato più volte sia in normal che hero.

**Comment by Gargarensis** [comment]
Puoi darmi più dettagli? Gli npc sono http://wotlk.openwow.com/npc=26536 ?
La recipe qual'è? Dove posso trovare a chance di drop?

**Comment by Irome** [comment]
Ti rispondo io al report perchè avevo chiesto io di riportarlo.
E' un bug presente in molti server, e oltre a questo altri mobs utilissimi per il farm che sono sparsi nelle zone wotlk non droppano nulla, magari ve li riporterò un pò alla volta.

Allora, i Mobs in questione sono i Mindless Servant, si trovano sopratutto all'entrata di Utgarde Pinnacle, sono degli scheletri che droppano items grigi, verdi e blu utili per enchanting, e delle stoffe (Frostweave Cloth) utili per tailoring.

Ci sono tanti loots che droppano, e non so se riuscite a inserirli tutti, ma l'importante è che droppino item, grigi, verdi e blu più le Frostweave Cloth. Qui di sotto posto il link che fa vedere i loot:

https://wow.freakz.ro/npc_finder.php?npc=26536

La percentuale precisa dei loots degli items e delle stoffe non la ricordo, ma so che arrivavano a droppare fino a 7 Frostweave Cloth, 3-4 item verdi più uno blu per volta. inoltre respawnavano molto velocemente.

**Comment by Gargarensis** [comment]
C'erano già delle referenze, presumo siano giuste, ma ho aggiustato un po' le percentuali e le quantità secondo il link che mi hai mandato

**Comment by Irome** [comment]
Ho testato per lungo tempo gli scheletri e oltre alla [Salted Venison], raramente qualche [Frostweave Cloth] e qualche item grigio non droppano nulla, nell'offy droppavano in grandi quantità item verdi da disenchantare, e frequentemente anche quelli blu, non so le percentuali precise ma sicuramente nello stato attuale non è corretto.
