### ISSUE TITLE
Skin Crossfaction

### ISSUE THREAD

**Issue by Ualock** [AzerothShard/AzerothShard-Issues-ita#90]
Non so dove lamentarmi mi è stato suggerito qui: è possibile rimuovere sta schifezza delle skin orda sui player ally e viceversa?

**Comment by mik1893** [comment]
sta "schifezza" e' stata fatta su richiesta di diversi player, ed e stata implementata persino su offy in espansioni piu recenti. La stiamo migliorando aggiungendo dei morph mirati per combinazioni di razza/classe.
Se vuoi proporre di rimuoverla, rivolgiti allo staff tramite forum o altri canali di supporto (non il bug tracker..)
