### ISSUE TITLE
Forme Druido

### ISSUE THREAD

**Issue by Scorpio96** [AzerothShard/AzerothShard-Issues-ita#91]
Come da titolo , le skin di alcune forme del druido come la swift flight form e la acquatic form scompaiono visivamente , pertanto vi chiedo di fixarle al piu presto

**Comment by Hollvedel** [comment]
Ho notato che accade quando si cambia zona (non solo regione), ed è solo un bug grafico. La form funziona a dovere, ma il dudu appare come elfo (immagino lo stesso accada per i tauren) pur con le caratteristiche della form animale.

**Comment by mik1893** [comment]
scusatemi ragazzi, mea culpa. Mi son lasciato prendere la mano col sistema del morph del crossfaction... ve lo rimetto a posto asap

**Comment by mik1893** [comment]
ok, dovrei averlo fixato. lo faccio mettere su da @Yehonal al prossimo restart
