### ISSUE TITLE
[quest] finale chain son of hodir

### ISSUE THREAD

**Issue by Hollvedel** [AzerothShard/AzerothShard-Issues-ita#92]
Alla fine della chain vengono attribuiti 22000 punti di reputazione e si diventa... hated. Allego screen.
![wowscrnshot_082416_232741](https://cloud.githubusercontent.com/assets/21138303/17949034/d7a7b5a2-6a53-11e6-946c-1860ee3f60f6.jpg)

**Comment by DantestyleXD** [comment]
Dai mob che hai ucciso nella quest prima, si droppa un item che attiva la quest che permette di continuare la chain
Gli NPCs in questione sono -> (http://www.wowhead.com/npc=29375) e droppano questo item (http://www.wowhead.com/item=41556).

**Comment by Hollvedel** [comment]
fatta anche quella quest
