### ISSUE TITLE
Shamy enha test

### ISSUE THREAD

**Issue by latitante** [AzerothShard/AzerothShard-Issues-ita#95]
Buona sera , il problema che non va con il mio shamy enha sono i danni che su azeroth sono molto diminuiti (Gioco lo shamy enha da 5 anni +)
Stormstike attivando tutto il massimo di  crit è di  2k 3k  invece giocando su soc ,wow is ,warmane  x 10 e x 20  e adesso su at da full rele facevo  questi danni e da full wrath  riuscivo in un massimo di 5k di critt sui full pvp e 7 k e mezzo base sui i pve 
Qui ho fatto 3000 duelli e vedo che il pg con full equip pve  critto  massimo  3 k  e me piglio le botte della madonna sui 7 k con 1300 resi + ( va bhè essendo full pve ci puo stare) 
Risolvete  perché sti miseri danni non si possono vedere con equip wrath

**Comment by xlollomanx** [comment]
In report fatto cosi non vuol dire assolutamente niente. É possible che l'enha fosse buggato (quasi sicuro) anche sull' altro core. Per poter essere preso in considerazione questo report devi scrivere le formule ( prese da un sito con valori wotlk attendibili) scrivere quanto fanno su questo core le spell e quanto invece dovrebbero fare secondo i tuoi calcoli.

**Comment by latitante** [comment]
Sull' altro corse da full wrath ho una base a colpo di 3500 qui ne faccio
massimo 2000 i danni sono ultra ridotti è l unico shard che non fa danni
fatevi uno shamy su  at warmane  o quello che sia è vedere che i danni che
fate li da relè suazeroth da wrath anche crittando la nonna da Sopra la
sedia non faccio una Sega di danno.. Provate a risolvere o io e i miei
amici ritorniamo su at

Il 29 Ago 2016 14:52, "xlollomanx" <notifications@github.com> ha scritto:

**Comment by xlollomanx** [comment]
Devi mettere dei calcoli seri come ti ho detto prima, finche fai post cosi nessuno prenderà in modo serio questo report. Segui il modello che ha scritto @mik1893 qui https://github.com/AzerothShard/AzerothShard-Issues-ita/issues/42 (scritto per war ma la dinamica è sempre la stessa).
