### ISSUE TITLE
[quest] Mastery of the charge

### ISSUE THREAD

**Issue by tranex01** [AzerothShard/AzerothShard-Issues-ita#97]
Durante lo svolgimento delle quest di argent tournament ho riscontrato il seguente bug.

Mastery of the charge è la quest.

In pratica bisogna caricare 2 volte un bersaglio che è vulnerabile al Charge con arma e cavallo degli A.T. 
La spell charge funziona ma non mi assegna l'azione compiuta.

**Comment by Deteroch** [comment]
Ciao, la quest "Mastery of the charge" anzitutto funziona perfettamente. Si divide in due parti molto semplici: la prima è parlare con l'npc Rugan Steelbelly che ti spiegherà quello che dovrai fare nel dettaglio, la seconda parte non è un semplice charge ma charge sul bersaglio indebolito quindi prima di fare charge sul bersaglio dovrai applicare una volta Shield-Breaker che toglierà l'unica stack di armor al bersaglio, dopodiché una volta indebolito potrai caricarlo. Testato oggi sul reame principale.
