### ISSUE TITLE
[porting] manca Maul al druido

### ISSUE THREAD

**Issue by alliancealiena** [AzerothShard/AzerothShard-Issues-ita#99]
nel porting non viene copiata l'abilità base "Maul" del druido che pertanto non può essere neanche trainata dal trainer perchè non hai il rank 1.

**Comment by ghost1988** [comment]
Apri ticket ingame per risolvere

**Comment by ShinDarth** [comment]
essendo un problema specifico del player e non un bug del gioco, chiudo qui.
